### ISSUE TITLE
High pitch noise on raspiAusio Muse Luxe

### ISSUE THREAD

**Issue by sophof** [esphome/media-players#17]
See title. After installing the yaml here the Muse Luxe emits a very audible high pitched tone when not playing anything. It was not present with the default firmware, so i assume it has something to do with the settings. But THere's not that much to fiddle with as far as I can find.

Note, I'm not that young anymore, so I assume most people will be able to hear it, but it is definitely on the 'edge'.

**Comment by feutl** [comment]
Got mine today, installed esphome, the pitching noise is really annoying.
Installing squeezlite firmware and nothing - just pure silence ;)

**Comment by sophof** [comment]
Interesting, do you mean this firmware?: https://github.com/sle118/squeezelite-esp32
I think it would be interesting to figure out what the cause is though, since I'm not the only one having this issue I would conclude the current yaml is unusable.

**Comment by feutl** [comment]
If you play a song and put in on pause - the pitch noise disappears ;)

I used the one which comes with the webinstaller from paulus
https://paulusschoutsen.nl/squeezelite-esp32-install/

**Comment by marcelveldt** [comment]
Investigated this issue today and found the bug. The muting control is now tied to the AMP power pin, meaning that when you mute the media player, the power will be shutdown from the AMP. If the amplifier is still powered while there's no audio sent to the DAC, you will hear that high pitch noise.

So final solution if that we should fix this this in the ESPHome audio component so the mute is assigned to the DAC's mute control and maybe a separate power control/switch to power the amplifier. This however takes a fair amount of time due to some needed rework needed to the ESPHome component.

Short time solution is to simply mute the media player while not in use.
If you use Music Assistant it will automatically mute the player on "power off" so this is handled for you.

**Comment by sophof** [comment]
Thanks, I was just testing a few things right now and realised that via Music Assistant powering off worked, so I'll use that for the time being :)

**Comment by jkms** [comment]
Any update on this?

**Comment by jesserockz** [comment]
Hello,

We have archived this repo as the files have moved to https://github.com/esphome/firmware

If you install the latest ESPHome version and your issue still exists, please open an issue there.

Cheers,
Jesse
